# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Aug 27 22:29:27 2006
#      by: PyQt4 UI code generator 4.0.1
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(QtCore.QSize(QtCore.QRect(0,0,692,597).size()).expandedTo(MainWindow.minimumSizeHint()))
        MainWindow.setWindowIcon(QtGui.QIcon("logo.png"))

        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setMargin(0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")

        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")

        self.mediaTab = QtGui.QWidget()
        self.mediaTab.setObjectName("mediaTab")

        self.hboxlayout = QtGui.QHBoxLayout(self.mediaTab)
        self.hboxlayout.setMargin(9)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")

        self.hardwareFrame = QtGui.QFrame(self.mediaTab)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(7),QtGui.QSizePolicy.Policy(7))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hardwareFrame.sizePolicy().hasHeightForWidth())
        self.hardwareFrame.setSizePolicy(sizePolicy)

        palette = QtGui.QPalette()
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(0),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(1),QtGui.QColor(170,170,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(3),QtGui.QColor(212,212,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(4),QtGui.QColor(85,85,127))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(5),QtGui.QColor(113,113,170))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(6),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(8),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(10),QtGui.QColor(170,170,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(12),QtGui.QColor(103,141,178))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,238))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(15),QtGui.QColor(82,24,139))
        palette.setColor(QtGui.QPalette.Active,QtGui.QPalette.ColorRole(16),QtGui.QColor(212,212,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(0),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(1),QtGui.QColor(170,170,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(3),QtGui.QColor(212,212,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(4),QtGui.QColor(85,85,127))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(5),QtGui.QColor(113,113,170))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(6),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(8),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(9),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(10),QtGui.QColor(170,170,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(12),QtGui.QColor(103,141,178))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,238))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(15),QtGui.QColor(82,24,139))
        palette.setColor(QtGui.QPalette.Inactive,QtGui.QPalette.ColorRole(16),QtGui.QColor(212,212,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(0),QtGui.QColor(85,85,127))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(1),QtGui.QColor(170,170,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(2),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(3),QtGui.QColor(212,212,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(4),QtGui.QColor(85,85,127))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(5),QtGui.QColor(113,113,170))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(6),QtGui.QColor(85,85,127))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(7),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(8),QtGui.QColor(85,85,127))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(9),QtGui.QColor(170,170,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(10),QtGui.QColor(170,170,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(11),QtGui.QColor(0,0,0))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(12),QtGui.QColor(86,117,148))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(13),QtGui.QColor(255,255,255))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(14),QtGui.QColor(0,0,238))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(15),QtGui.QColor(82,24,139))
        palette.setColor(QtGui.QPalette.Disabled,QtGui.QPalette.ColorRole(16),QtGui.QColor(212,212,255))
        self.hardwareFrame.setPalette(palette)
        self.hardwareFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.hardwareFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.hardwareFrame.setObjectName("hardwareFrame")
        self.hboxlayout.addWidget(self.hardwareFrame)

        self.widget = QtGui.QWidget(self.mediaTab)
        self.widget.setObjectName("widget")

        self.vboxlayout1 = QtGui.QVBoxLayout(self.widget)
        self.vboxlayout1.setMargin(0)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setObjectName("vboxlayout1")

        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setSpacing(0)
        self.vboxlayout2.setObjectName("vboxlayout2")

        self.mediaList = QtGui.QListView(self.widget)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(5),QtGui.QSizePolicy.Policy(5))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mediaList.sizePolicy().hasHeightForWidth())
        self.mediaList.setSizePolicy(sizePolicy)
        self.mediaList.setObjectName("mediaList")
        self.vboxlayout2.addWidget(self.mediaList)
        self.vboxlayout1.addLayout(self.vboxlayout2)

        self.mediaStack = QtGui.QStackedWidget(self.widget)
        self.mediaStack.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mediaStack.setFrameShadow(QtGui.QFrame.Sunken)
        self.mediaStack.setObjectName("mediaStack")

        self.page = QtGui.QWidget()
        self.page.setObjectName("page")

        self.label = QtGui.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10,10,321,111))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.mediaStack.addWidget(self.page)

        self.diskPage = QtGui.QWidget()
        self.diskPage.setObjectName("diskPage")

        self.vboxlayout3 = QtGui.QVBoxLayout(self.diskPage)
        self.vboxlayout3.setMargin(9)
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setObjectName("vboxlayout3")

        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")

        self.diskLabel = QtGui.QLabel(self.diskPage)

        font = QtGui.QFont(self.diskLabel.font())
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.diskLabel.setFont(font)
        self.diskLabel.setObjectName("diskLabel")
        self.hboxlayout1.addWidget(self.diskLabel)

        self.diskEjectButton = QtGui.QPushButton(self.diskPage)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diskEjectButton.sizePolicy().hasHeightForWidth())
        self.diskEjectButton.setSizePolicy(sizePolicy)
        self.diskEjectButton.setIcon(QtGui.QIcon("eject.png"))
        self.diskEjectButton.setObjectName("diskEjectButton")
        self.hboxlayout1.addWidget(self.diskEjectButton)
        self.vboxlayout3.addLayout(self.hboxlayout1)

        self.diskDescriptionLabel = QtGui.QLabel(self.diskPage)

        font = QtGui.QFont(self.diskDescriptionLabel.font())
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.diskDescriptionLabel.setFont(font)
        self.diskDescriptionLabel.setObjectName("diskDescriptionLabel")
        self.vboxlayout3.addWidget(self.diskDescriptionLabel)

        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setObjectName("hboxlayout2")

        self.diskBrowseImageButton = QtGui.QPushButton(self.diskPage)
        self.diskBrowseImageButton.setObjectName("diskBrowseImageButton")
        self.hboxlayout2.addWidget(self.diskBrowseImageButton)

        spacerItem = QtGui.QSpacerItem(20,20,QtGui.QSizePolicy.Preferred,QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem)

        self.diskBrowseDirectoryButton = QtGui.QPushButton(self.diskPage)
        self.diskBrowseDirectoryButton.setObjectName("diskBrowseDirectoryButton")
        self.hboxlayout2.addWidget(self.diskBrowseDirectoryButton)
        self.vboxlayout3.addLayout(self.hboxlayout2)

        self.diskHistoryBox = QtGui.QComboBox(self.diskPage)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(1),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diskHistoryBox.sizePolicy().hasHeightForWidth())
        self.diskHistoryBox.setSizePolicy(sizePolicy)
        self.diskHistoryBox.setEditable(True)
        self.diskHistoryBox.setMaxCount(100)
        self.diskHistoryBox.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.diskHistoryBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.diskHistoryBox.setMinimumContentsLength(20)
        self.diskHistoryBox.setObjectName("diskHistoryBox")
        self.vboxlayout3.addWidget(self.diskHistoryBox)

        spacerItem1 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout3.addItem(spacerItem1)
        self.mediaStack.addWidget(self.diskPage)

        self.cartPage = QtGui.QWidget()
        self.cartPage.setObjectName("cartPage")

        self.vboxlayout4 = QtGui.QVBoxLayout(self.cartPage)
        self.vboxlayout4.setMargin(9)
        self.vboxlayout4.setSpacing(6)
        self.vboxlayout4.setObjectName("vboxlayout4")

        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setObjectName("hboxlayout3")

        self.cartLabel = QtGui.QLabel(self.cartPage)

        font = QtGui.QFont(self.cartLabel.font())
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setWeight(75)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(True)
        self.cartLabel.setFont(font)
        self.cartLabel.setObjectName("cartLabel")
        self.hboxlayout3.addWidget(self.cartLabel)

        self.cartEjectButton = QtGui.QPushButton(self.cartPage)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(0),QtGui.QSizePolicy.Policy(0))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cartEjectButton.sizePolicy().hasHeightForWidth())
        self.cartEjectButton.setSizePolicy(sizePolicy)
        self.cartEjectButton.setIcon(QtGui.QIcon("eject.png"))
        self.cartEjectButton.setObjectName("cartEjectButton")
        self.hboxlayout3.addWidget(self.cartEjectButton)
        self.vboxlayout4.addLayout(self.hboxlayout3)

        self.cartDescriptionLabel = QtGui.QLabel(self.cartPage)

        font = QtGui.QFont(self.cartDescriptionLabel.font())
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.cartDescriptionLabel.setFont(font)
        self.cartDescriptionLabel.setObjectName("cartDescriptionLabel")
        self.vboxlayout4.addWidget(self.cartDescriptionLabel)

        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setObjectName("hboxlayout4")

        self.cartBrowseImageButton = QtGui.QPushButton(self.cartPage)
        self.cartBrowseImageButton.setObjectName("cartBrowseImageButton")
        self.hboxlayout4.addWidget(self.cartBrowseImageButton)

        spacerItem2 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout4.addItem(spacerItem2)
        self.vboxlayout4.addLayout(self.hboxlayout4)

        self.cartHistoryBox = QtGui.QComboBox(self.cartPage)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Policy(1),QtGui.QSizePolicy.Policy(1))
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cartHistoryBox.sizePolicy().hasHeightForWidth())
        self.cartHistoryBox.setSizePolicy(sizePolicy)
        self.cartHistoryBox.setEditable(True)
        self.cartHistoryBox.setMaxCount(100)
        self.cartHistoryBox.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.cartHistoryBox.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.cartHistoryBox.setMinimumContentsLength(20)
        self.cartHistoryBox.setObjectName("cartHistoryBox")
        self.vboxlayout4.addWidget(self.cartHistoryBox)

        spacerItem3 = QtGui.QSpacerItem(20,40,QtGui.QSizePolicy.Minimum,QtGui.QSizePolicy.Expanding)
        self.vboxlayout4.addItem(spacerItem3)
        self.mediaStack.addWidget(self.cartPage)
        self.vboxlayout1.addWidget(self.mediaStack)

        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setMargin(0)
        self.hboxlayout5.setSpacing(6)
        self.hboxlayout5.setObjectName("hboxlayout5")

        spacerItem4 = QtGui.QSpacerItem(40,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout5.addItem(spacerItem4)

        self.resetButton = QtGui.QPushButton(self.widget)
        self.resetButton.setObjectName("resetButton")
        self.hboxlayout5.addWidget(self.resetButton)
        self.vboxlayout1.addLayout(self.hboxlayout5)
        self.hboxlayout.addWidget(self.widget)
        self.tabWidget.addTab(self.mediaTab, "")

        self.inputTab = QtGui.QWidget()
        self.inputTab.setObjectName("inputTab")
        self.tabWidget.addTab(self.inputTab, "")

        self.videoTab = QtGui.QWidget()
        self.videoTab.setObjectName("videoTab")

        self.widget1 = QtGui.QWidget(self.videoTab)
        self.widget1.setGeometry(QtCore.QRect(51,44,251,364))
        self.widget1.setObjectName("widget1")

        self.gridlayout = QtGui.QGridLayout(self.widget1)
        self.gridlayout.setMargin(0)
        self.gridlayout.setSpacing(0)
        self.gridlayout.setObjectName("gridlayout")

        self.vboxlayout5 = QtGui.QVBoxLayout()
        self.vboxlayout5.setMargin(6)
        self.vboxlayout5.setSpacing(0)
        self.vboxlayout5.setObjectName("vboxlayout5")

        self.blurLabel = QtGui.QLabel(self.widget1)
        self.blurLabel.setObjectName("blurLabel")
        self.vboxlayout5.addWidget(self.blurLabel)

        self.blurSlider = QtGui.QSlider(self.widget1)
        self.blurSlider.setMaximum(100)
        self.blurSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blurSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.blurSlider.setTickInterval(10)
        self.blurSlider.setObjectName("blurSlider")
        self.vboxlayout5.addWidget(self.blurSlider)
        self.gridlayout.addLayout(self.vboxlayout5,1,0,1,1)

        self.blurSpinBox = QtGui.QSpinBox(self.widget1)
        self.blurSpinBox.setMaximum(100)
        self.blurSpinBox.setSingleStep(5)
        self.blurSpinBox.setObjectName("blurSpinBox")
        self.gridlayout.addWidget(self.blurSpinBox,1,1,1,1)

        self.vboxlayout6 = QtGui.QVBoxLayout()
        self.vboxlayout6.setMargin(6)
        self.vboxlayout6.setSpacing(0)
        self.vboxlayout6.setObjectName("vboxlayout6")

        self.gammaLabel = QtGui.QLabel(self.widget1)
        self.gammaLabel.setObjectName("gammaLabel")
        self.vboxlayout6.addWidget(self.gammaLabel)

        self.gammaSlider = QtGui.QSlider(self.widget1)
        self.gammaSlider.setMaximum(100)
        self.gammaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gammaSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.gammaSlider.setTickInterval(10)
        self.gammaSlider.setObjectName("gammaSlider")
        self.vboxlayout6.addWidget(self.gammaSlider)
        self.gridlayout.addLayout(self.vboxlayout6,3,0,1,1)

        self.glowSpinBox = QtGui.QSpinBox(self.widget1)
        self.glowSpinBox.setMaximum(100)
        self.glowSpinBox.setSingleStep(5)
        self.glowSpinBox.setObjectName("glowSpinBox")
        self.gridlayout.addWidget(self.glowSpinBox,2,1,1,1)

        self.vboxlayout7 = QtGui.QVBoxLayout()
        self.vboxlayout7.setMargin(6)
        self.vboxlayout7.setSpacing(0)
        self.vboxlayout7.setObjectName("vboxlayout7")

        self.contrastLabel = QtGui.QLabel(self.widget1)
        self.contrastLabel.setObjectName("contrastLabel")
        self.vboxlayout7.addWidget(self.contrastLabel)

        self.contrastSlider = QtGui.QSlider(self.widget1)
        self.contrastSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlider.setObjectName("contrastSlider")
        self.vboxlayout7.addWidget(self.contrastSlider)
        self.gridlayout.addLayout(self.vboxlayout7,5,0,1,1)

        self.vboxlayout8 = QtGui.QVBoxLayout()
        self.vboxlayout8.setMargin(6)
        self.vboxlayout8.setSpacing(0)
        self.vboxlayout8.setObjectName("vboxlayout8")

        self.glowLabel = QtGui.QLabel(self.widget1)
        self.glowLabel.setObjectName("glowLabel")
        self.vboxlayout8.addWidget(self.glowLabel)

        self.glowSlider = QtGui.QSlider(self.widget1)
        self.glowSlider.setMaximum(100)
        self.glowSlider.setOrientation(QtCore.Qt.Horizontal)
        self.glowSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.glowSlider.setTickInterval(10)
        self.glowSlider.setObjectName("glowSlider")
        self.vboxlayout8.addWidget(self.glowSlider)
        self.gridlayout.addLayout(self.vboxlayout8,2,0,1,1)

        self.noiseSpinBox = QtGui.QDoubleSpinBox(self.widget1)
        self.noiseSpinBox.setObjectName("noiseSpinBox")
        self.gridlayout.addWidget(self.noiseSpinBox,6,1,1,1)

        self.vboxlayout9 = QtGui.QVBoxLayout()
        self.vboxlayout9.setMargin(6)
        self.vboxlayout9.setSpacing(0)
        self.vboxlayout9.setObjectName("vboxlayout9")

        self.brightnessLabel = QtGui.QLabel(self.widget1)
        self.brightnessLabel.setObjectName("brightnessLabel")
        self.vboxlayout9.addWidget(self.brightnessLabel)

        self.brightnessSlider = QtGui.QSlider(self.widget1)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.vboxlayout9.addWidget(self.brightnessSlider)
        self.gridlayout.addLayout(self.vboxlayout9,4,0,1,1)

        self.gammaSpinBox = QtGui.QDoubleSpinBox(self.widget1)
        self.gammaSpinBox.setMaximum(5.0)
        self.gammaSpinBox.setMinimum(0.0)
        self.gammaSpinBox.setObjectName("gammaSpinBox")
        self.gridlayout.addWidget(self.gammaSpinBox,3,1,1,1)

        self.vboxlayout10 = QtGui.QVBoxLayout()
        self.vboxlayout10.setMargin(6)
        self.vboxlayout10.setSpacing(0)
        self.vboxlayout10.setObjectName("vboxlayout10")

        self.noiseLabel = QtGui.QLabel(self.widget1)
        self.noiseLabel.setObjectName("noiseLabel")
        self.vboxlayout10.addWidget(self.noiseLabel)

        self.noiseSlider = QtGui.QSlider(self.widget1)
        self.noiseSlider.setOrientation(QtCore.Qt.Horizontal)
        self.noiseSlider.setObjectName("noiseSlider")
        self.vboxlayout10.addWidget(self.noiseSlider)
        self.gridlayout.addLayout(self.vboxlayout10,6,0,1,1)

        self.vboxlayout11 = QtGui.QVBoxLayout()
        self.vboxlayout11.setMargin(6)
        self.vboxlayout11.setSpacing(0)
        self.vboxlayout11.setObjectName("vboxlayout11")

        self.scanlineLabel = QtGui.QLabel(self.widget1)
        self.scanlineLabel.setObjectName("scanlineLabel")
        self.vboxlayout11.addWidget(self.scanlineLabel)

        self.scanlineSlider = QtGui.QSlider(self.widget1)
        self.scanlineSlider.setMaximum(100)
        self.scanlineSlider.setOrientation(QtCore.Qt.Horizontal)
        self.scanlineSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.scanlineSlider.setTickInterval(10)
        self.scanlineSlider.setObjectName("scanlineSlider")
        self.vboxlayout11.addWidget(self.scanlineSlider)
        self.gridlayout.addLayout(self.vboxlayout11,0,0,1,1)

        self.brightnessSpinBox = QtGui.QDoubleSpinBox(self.widget1)
        self.brightnessSpinBox.setObjectName("brightnessSpinBox")
        self.gridlayout.addWidget(self.brightnessSpinBox,4,1,1,1)

        self.contrastSpinBox = QtGui.QDoubleSpinBox(self.widget1)
        self.contrastSpinBox.setObjectName("contrastSpinBox")
        self.gridlayout.addWidget(self.contrastSpinBox,5,1,1,1)

        self.scanlineSpinBox = QtGui.QSpinBox(self.widget1)
        self.scanlineSpinBox.setMaximum(100)
        self.scanlineSpinBox.setSingleStep(5)
        self.scanlineSpinBox.setProperty("value",QtCore.QVariant(0))
        self.scanlineSpinBox.setObjectName("scanlineSpinBox")
        self.gridlayout.addWidget(self.scanlineSpinBox,0,1,1,1)
        self.tabWidget.addTab(self.videoTab, "")

        self.audioTab = QtGui.QWidget()
        self.audioTab.setObjectName("audioTab")
        self.tabWidget.addTab(self.audioTab, "")

        self.consoleTab = QtGui.QWidget()
        self.consoleTab.setObjectName("consoleTab")

        self.vboxlayout12 = QtGui.QVBoxLayout(self.consoleTab)
        self.vboxlayout12.setMargin(0)
        self.vboxlayout12.setSpacing(0)
        self.vboxlayout12.setObjectName("vboxlayout12")

        self.logText = QtGui.QTextEdit(self.consoleTab)
        self.logText.setReadOnly(True)
        self.logText.setObjectName("logText")
        self.vboxlayout12.addWidget(self.logText)

        self.consoleLineEdit = QtGui.QLineEdit(self.consoleTab)
        self.consoleLineEdit.setObjectName("consoleLineEdit")
        self.vboxlayout12.addWidget(self.consoleLineEdit)
        self.tabWidget.addTab(self.consoleTab, "")
        self.vboxlayout.addWidget(self.tabWidget)

        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setMargin(0)
        self.hboxlayout6.setSpacing(6)
        self.hboxlayout6.setObjectName("hboxlayout6")

        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setMargin(6)
        self.hboxlayout7.setSpacing(0)
        self.hboxlayout7.setObjectName("hboxlayout7")

        self.playButton = QtGui.QPushButton(self.centralwidget)
        self.playButton.setIcon(QtGui.QIcon("play.png"))
        self.playButton.setCheckable(True)
        self.playButton.setObjectName("playButton")
        self.hboxlayout7.addWidget(self.playButton)

        self.pauseButton = QtGui.QPushButton(self.centralwidget)
        self.pauseButton.setIcon(QtGui.QIcon("pause.png"))
        self.pauseButton.setCheckable(True)
        self.pauseButton.setObjectName("pauseButton")
        self.hboxlayout7.addWidget(self.pauseButton)

        self.stopButton = QtGui.QPushButton(self.centralwidget)
        self.stopButton.setIcon(QtGui.QIcon("stop.png"))
        self.stopButton.setCheckable(True)
        self.stopButton.setChecked(True)
        self.stopButton.setObjectName("stopButton")
        self.hboxlayout7.addWidget(self.stopButton)

        self.forwardButton = QtGui.QPushButton(self.centralwidget)
        self.forwardButton.setIcon(QtGui.QIcon("forward.png"))
        self.forwardButton.setCheckable(True)
        self.forwardButton.setObjectName("forwardButton")
        self.hboxlayout7.addWidget(self.forwardButton)
        self.hboxlayout6.addLayout(self.hboxlayout7)

        spacerItem5 = QtGui.QSpacerItem(351,20,QtGui.QSizePolicy.Expanding,QtGui.QSizePolicy.Minimum)
        self.hboxlayout6.addItem(spacerItem5)
        self.vboxlayout.addLayout(self.hboxlayout6)
        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,692,29))
        self.menubar.setObjectName("menubar")

        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")

        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0,575,692,22))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.action_AboutCatapult = QtGui.QAction(MainWindow)
        self.action_AboutCatapult.setObjectName("action_AboutCatapult")

        self.action_Quit = QtGui.QAction(MainWindow)
        self.action_Quit.setObjectName("action_Quit")

        self.action_AboutQt = QtGui.QAction(MainWindow)
        self.action_AboutQt.setObjectName("action_AboutQt")

        self.action_HelpSetup = QtGui.QAction(MainWindow)
        self.action_HelpSetup.setObjectName("action_HelpSetup")

        self.action_HelpUser = QtGui.QAction(MainWindow)
        self.action_HelpUser.setObjectName("action_HelpUser")
        self.menu_File.addAction(self.action_Quit)
        self.menu_Help.addAction(self.action_HelpSetup)
        self.menu_Help.addAction(self.action_HelpUser)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_AboutCatapult)
        self.menu_Help.addAction(self.action_AboutQt)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.mediaStack.setCurrentIndex(0)
        QtCore.QObject.connect(self.tabWidget,QtCore.SIGNAL("currentChanged(int)"),self.consoleLineEdit.setFocus)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "openMSX Catapult", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "The cartridge slots, disk drives and cassette player of the currently active MSX are shown in the list above. After you select one of them, you can insert a cartridge, disk or cassette in this panel. ", None, QtGui.QApplication.UnicodeUTF8))
        self.diskLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:16pt; font-weight:600; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">Disk A</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.diskDescriptionLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:12pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Disk image of 720K</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.diskBrowseImageButton.setText(QtGui.QApplication.translate("MainWindow", "Browse Disk &Images...", None, QtGui.QApplication.UnicodeUTF8))
        self.diskBrowseDirectoryButton.setText(QtGui.QApplication.translate("MainWindow", "Browse &Directories...", None, QtGui.QApplication.UnicodeUTF8))
        self.cartLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:16pt; font-weight:600; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:400;\">Cartridge A</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cartDescriptionLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head><meta name=\"qrichtext\" content=\"1\" /></head><body style=\" white-space: pre-wrap; font-family:Sans Serif; font-size:12pt; font-weight:400; font-style:normal; text-decoration:none;\"><p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ROM image of 256K</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cartBrowseImageButton.setText(QtGui.QApplication.translate("MainWindow", "Browse ROM &Images...", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mediaTab), QtGui.QApplication.translate("MainWindow", "Media", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inputTab), QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.blurLabel.setText(QtGui.QApplication.translate("MainWindow", "Blur:", None, QtGui.QApplication.UnicodeUTF8))
        self.gammaLabel.setText(QtGui.QApplication.translate("MainWindow", "Gamma Correction:", None, QtGui.QApplication.UnicodeUTF8))
        self.contrastLabel.setText(QtGui.QApplication.translate("MainWindow", "Contrast:", None, QtGui.QApplication.UnicodeUTF8))
        self.glowLabel.setText(QtGui.QApplication.translate("MainWindow", "Glow:", None, QtGui.QApplication.UnicodeUTF8))
        self.brightnessLabel.setText(QtGui.QApplication.translate("MainWindow", "Brightness:", None, QtGui.QApplication.UnicodeUTF8))
        self.noiseLabel.setText(QtGui.QApplication.translate("MainWindow", "Noise:", None, QtGui.QApplication.UnicodeUTF8))
        self.scanlineLabel.setText(QtGui.QApplication.translate("MainWindow", "Scanline:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.videoTab), QtGui.QApplication.translate("MainWindow", "Video", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.audioTab), QtGui.QApplication.translate("MainWindow", "Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.consoleTab), QtGui.QApplication.translate("MainWindow", "Console", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_AboutCatapult.setText(QtGui.QApplication.translate("MainWindow", "&About openMSX Catapult", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_AboutQt.setText(QtGui.QApplication.translate("MainWindow", "About &Qt", None, QtGui.QApplication.UnicodeUTF8))
        self.action_HelpSetup.setText(QtGui.QApplication.translate("MainWindow", "openMSX &Setup Guide", None, QtGui.QApplication.UnicodeUTF8))
        self.action_HelpUser.setText(QtGui.QApplication.translate("MainWindow", "openMSX &User\'s Manual", None, QtGui.QApplication.UnicodeUTF8))
